### ISSUE TITLE
Request for configurable style guides

### ISSUE THREAD

**Issue by ro0sterjam** [entur/mapstruct-spi-protobuf#132]
Hi, this project is perfect for us except one thing: we are using the UberV2 style guide rather than Google's and thus our [enums are mapped differently](https://github.com/entur/mapstruct-spi-protobuf/issues).

Instead of:

```
enum TripType {
  TRIP_TYPE_UNSPECIFIED = 0;
  TRIP_TYPE_UBERX = 1;
  TRIP_TYPE_POOL = 2;
}
```

We have:

```
enum TripType {
  TRIP_TYPE_INVALID = 0;
  TRIP_TYPE_UBERX = 1;
  TRIP_TYPE_POOL = 2;
}
```

Would it at all be possible to either make this project configurable to different style guides? Or at the very least enable for configuring the enum suffix for unspecified enum values?

**Comment by seime** [comment]
Merged, thanx

**Comment by ro0sterjam** [comment]
Thanks!
