### ISSUE TITLE
fail in gradle build since version 1.20

### ISSUE THREAD

**Issue by jeffawx** [entur/mapstruct-spi-protobuf#163]
> Could not find no.entur.mapstruct.spi:protobuf-support:1.20.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/no/entur/mapstruct/spi/protobuf-support/1.20/protobuf-support-1.20.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.

1.19 is fine

**Comment by seime** [comment]
Replaced by support-standard or support-lite depending on your need
