### ISSUE TITLE
Couldn't retrieve @Mapper annotation issue

### ISSUE THREAD

**Issue by GaniduAsh** [entur/mapstruct-spi-protobuf#184]
Using following dependencies to integrate proto-buf mapper  in an android project
 
org.mapstruct:mapstruct:1.4.2.Final
org.mapstruct:mapstruct-processor:1.4.2.Final
no.entur.mapstruct.spi:protobuf-spi-impl:1.23

but once i add no.entur.mapstruct.spi:protobuf-spi-impl:1.23 dependency, an error prompts 
Couldn't retrieve @Mapper annotation

This is an existing project i have used json to POJO and vice versa. Since we have decided to go ahead with proto instead of JSON, i was trying to integrate mapstruct-spi-protobuf module.

What could be the reason ? could this has prompted due to a module conflict ?

**Comment by seime** [comment]
Did you add them all as dependencies? Or like this (notice the `annotationProcessor`) 

```
implementation"org.mapstruct:mapstruct:${mapstructVersion}"
annotationProcessor"org.mapstruct:mapstruct-processor:${mapstructVersion}"
annotationProcessor"no.entur.mapstruct.spi:protobuf-spi-impl:LATEST.VERSION"
```

**Comment by renyijiu** [comment]
I also encountered this problem，it looks `no.entur.mapstruct.spi:protobuf-spi-impl:1.23` depend on `mapstruct:1.5.0-beta2`, but mapstruct version `org.mapstruct:mapstruct:1.4.2.Final`, the two versions do not match, you can use `no.entur.mapstruct.spi:protobuf-spi-impl:1.21`

**Comment by seime** [comment]
Added a note to README about this
