### ISSUE TITLE
Please perform a release with newest MapStruct

### ISSUE THREAD

**Issue by mkjensen** [entur/mapstruct-spi-protobuf#208]
Current version (1.24) uses MapStruct 1.5.0.RC1 which has some bugs. I'm being hit by something related to imports for nested classes. It sounds like it is fixed in MapStruct 1.5.0.Final: https://github.com/mapstruct/mapstruct/releases/tag/1.5.0.Final

Your dependency bot has already pulled in MapStruct 1.5.1.Final.

Thanks.

**Comment by mkjensen** [comment]
Btw, I tried to work around this by forcing an upgrade of MapStruct:

`<annotationProcessorPaths>
    <path>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-processor</artifactId>
        <version>${mapstruct.version}</version>
    </path>
    <path>
        <groupId>no.entur.mapstruct.spi</groupId>
        <artifactId>protobuf-spi-impl</artifactId>
        <version>${entur-mapstruct.version}</version>
    </path>
</annotationProcessorPaths>`

It resulted in this error message:

`

**Comment by mkjensen** [comment]
I have found out that the bugs still exist in MapStruct 1.5.1.Final so a newer release of `protobuf-spi-impl` does not help at the moment. I have reported the issue at https://github.com/mapstruct/mapstruct/issues/2880.

**Comment by mkjensen** [comment]
MapStruct 1.5.2.Final has been released: https://github.com/mapstruct/mapstruct/releases/tag/1.5.2.Final

It would be nice with a new release of `protobuf-spi-impl` using that. Thanks.

**Comment by seime** [comment]
Released
