### ISSUE TITLE
ProtobufEnumMappingStrategy breaks for non-compliant protobuf

### ISSUE THREAD

**Issue by facboy** [entur/mapstruct-spi-protobuf#31]
The addition of this class has made this plugin unusable for us as many of our enums do not have the `_UNSPECIFIED` value.  Ideally our protobuf should follow the style guide but in reality there are often old, non-compliant definitions that cannot be updated easily.

Is there a way to disable it?

Also I haven't had time to test it, but I'm not sure you can just 'override `getDefaultEnumConstant()`' if you were using a different suffix, as

1. it's a static method so you can't override it
2. it's only invoked in the static initializer anyway to set `DEFAULT_ENUM_CONSTANT`, which is the only thing referred to in the rest of the class, so even if you could override it (which you can't) it would have no effect because nothing would ever invoke it.

**Comment by seime** [comment]
I think you are right, the override probably won't work or not even being accepted by the compiler.

The fix should be fairly easy to implement.

Regarding protos that do not follow the style guide; this should also be possible to support by doing a precense check on the computed enum constant.

Would you provide a PR for this fix? I'd be happy to merge it.

Reagrds

**Comment by seime** [comment]
Made `getDefaultEnumConstant` overridable

@facboy also see documentation; you can manually override mappings: https://mapstruct.org/documentation/stable/reference/html/#_mapping_enum_to_enum_types
