### ISSUE TITLE
Release for 1.6.3 permitted?

### ISSUE THREAD

**Issue by daniel-b2c2** [entur/mapstruct-spi-protobuf#472]
I see mapstruct 1.6.3 has been released and renovate bot has upgraded the pom accordingly.

Could somebody kindly perform a release for `mapstruct-spi-protobuf`? 🚀 

Many thanks

**Comment by daniel-b2c2** [comment]
Not sure if I'm supposed to tag the repo owners, presumably releases are something only the owner can perform. @erlendnils1 can you assist, or perhaps point me in the right direction: Are releases performed on request or do they have a schedule?

Kindest regards

**Comment by erlendnils1** [comment]
Thanks for the notification. Releases are only performed manually when there are only renovate changes. I have released and published 1.46 with the latest dependency updates now

**Comment by daniel-b2c2** [comment]
Amazing! Thank you! 🙇
