### ISSUE TITLE
protobuf-support version warning when building with Java 8

### ISSUE THREAD

**Issue by nbruno** [entur/mapstruct-spi-protobuf#98]
protobuf-support is specifying compiler.source and compiler.target of 8 but on a Java 8 project the following warning is emitted when building with Gradle:

> warning: /Users/user/.gradle/caches/modules-2/files-2.1/no.entur.mapstruct.spi/protobuf-support/1.14/9e9fa7bb5527bc949ed87122742344034eb8ff29/protobuf-support-1.14.jar(no/entur/abt/mapstruct/ProtobufStandardMappings.class): major version 53 is newer than 52, the highest major version supported by this compiler.
>   It is recommended that the compiler be upgraded.

Should the project be compiling with Java 8 instead of Java 9?

**Comment by seime** [comment]
Thank you for the report and sorry for the delay @nbruno .

Fix applied and new release completed.
